services:
  maincast-calendar-ruby: &maincast-calendar-ruby
    image: ghcr.io/${REPO_OWNER}/${REPO_NAME}:latest
    container_name: maincast-calendar-ruby-${COMMIT_HASH}
    restart: unless-stopped
    tty: true
    stdin_open: true
    env_file:
      - ./.env
    network_mode: host

  maincast-calendar-api:
    <<: *maincast-calendar-ruby
    container_name: maincast-calendar-api-${COMMIT_HASH}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p ${PORT} -b '0.0.0.0'"

  maincast-calendar-sidekiq:
    <<: *maincast-calendar-ruby
    container_name: maincast-calendar-sidekiq-${COMMIT_HASH}
    command: sidekiq
