name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "repository_name_lowercase=$(echo ${{ github.repository }} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "repository_owner_lowercase=$(echo ${{ github.repository }} | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "server_folder_path=/home/${{ secrets.SSH_USER }}/next-api-copy1" >> $GITHUB_ENV
          echo "docker_compose_file=docker-compose.staging.yml" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run linter
        run: |
          bundle exec rubocop
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.repository_owner_lowercase }}/${{ env.repository_name_lowercase }}:latest

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H '${{ secrets.SSH_HOST }}' >> ~/.ssh/known_hosts

      - name: Create project folder
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            if [ ! -d "${{ env.server_folder_path }}" ]; then
              sudo mkdir ${{ env.server_folder_path }}
              sudo chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ env.server_folder_path }}
            fi
          EOF

      - name: Copy docker-compose.yml
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ env.docker_compose_file }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.server_folder_path }}

      - name: Create .env
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            echo "
            REPOSITORY_OWNER_LOWERCASE='${{ env.repository_owner_lowercase }}'
            REPOSITORY_NAME_LOWERCASE='${{ env.repository_name_lowercase }}'
            SENTRY_DSN='${{ secrets.SENTRY_DSN }}'
            PRODUCTION_URL='${{ secrets.PRODUCTION_URL }}'
            STAGING_URL='${{ secrets.STAGING_URL }}'
            DATABASE_HOST='${{ secrets.DATABASE_HOST }}'
            DATABASE_NAME='${{ secrets.DATABASE_NAME }}' 
            STAGE_DATABASE_NAME='${{ secrets.STAGE_DATABASE_NAME }}'
            SECRET_KEY_BASE='${{ secrets.SECRET_KEY_BASE }}123' 
            DATABASE_USER='${{ secrets.DATABASE_USER}}' 
            DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}' 
            API_TOOLS_ACCESS_TOKEN='${{ secrets.API_TOOLS_ACCESS_TOKEN }}' 
            ROOT_API_URL='${{ secrets.ROOT_API_URL }}' 
            SMTP_DELIVERY_METHOD='smtp' 
            SMTP_USER_NAME='${{ secrets.SMTP_USER_NAME }}' 
            SMTP_PASSWORD='${{ secrets.SMTP_PASSWORD }}' 
            SMTP_HOST='${{ secrets.SMTP_HOST }}' 
            SMTP_PORT='${{ secrets.SMTP_PORT }}' 
            BASE_FRONT_URL='${{ secrets.BASE_FRONT_URL }}' 
            ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}' 
            ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}' 
            JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' 
            GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}' 
            GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}' 
            GOOGLE_ENCODED_SECRET_FILE='${{ secrets.GOOGLE_ENCODED_SECRET_FILE }}' 
            TELEGRAM_BOT='${{ secrets.TELEGRAM_BOT }}' 
            DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'
            DISCORD_CHANNEL_ID='${{ secrets.DISCORD_CHANNEL_ID }}'
            REDIS_URL='redis://localhost:6379/11'
            ACTION_CABLE_URL='ws://localhost:${{ secrets.PORT }}/cable'
            LANG=C.UTF-8
            RAILS_ENV=production
            RAILS_MIN_THREADS=1
            RAILS_MAX_THREADS=10
            WEB_CONCURRENCY=3
            SIDEKIQ_CONCURRENCY=5
            LC_CTYPE=en_US.UTF-8
            LC_ALL=en_US.UTF-8
            PORT=${{ secrets.PORT }}
            PATH='/home/${{ secrets.SSH_USER }}/.rbenv/bin:/home/${{ secrets.SSH_USER }}/.rbenv/shims:$PATH'
            " > ${{ env.server_folder_path }}/.env
          EOF

      - name: Run Docker
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            cd ${{ env.server_folder_path }}
            echo "${{ github.token }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker pull ghcr.io/${{ env.repository_owner_lowercase }}/${{ env.repository_name_lowercase }}:latest
            sudo docker stop maincast-calendar-ruby || true
            sudo docker stop maincast-calendar-api || true
            sudo docker stop maincast-calendar-sidekiq || true
            sudo docker stop maincast-calendar-discord-bot || true
            sudo docker stop maincast-calendar-telegram-bot || true
            sudo docker rm maincast-calendar-ruby || true
            sudo docker rm maincast-calendar-api || true
            sudo docker rm maincast-calendar-sidekiq || true
            sudo docker rm maincast-calendar-discord-bot || true
            sudo docker rm maincast-calendar-telegram-bot || true
            sudo docker compose -f ${{ env.docker_compose_file }} up -d
          EOF
