name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.0.2' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run linter
        run: |
          bundle exec rubocop
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            ssh-add ~/.ssh/id_rsa
            if [ ! -d "/home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}" ]; then
              mkdir /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
              chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
              git clone ${{ secrets.SSH_GITHUB_REPOSITORY }} /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
            fi
            cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}
            git checkout staging
            git pull origin staging
            
            export DATABASE_HOST='${{ secrets.DATABASE_HOST }}'
            export DATABASE_NAME='${{ secrets.DATABASE_NAME }}'
            export STAGE_DATABASE_NAME="${{ secrets.STAGE_DATABASE_NAME }}"
            export SECRET_KEY_BASE="${{ secrets.SECRET_KEY_BASE }}123"
            export DATABASE_USER="${{ secrets.DATABASE_USER}}"
            export DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"
            export API_TOOLS_ACCESS_TOKEN="${{ secrets.API_TOOLS_ACCESS_TOKEN }}"
            export ROOT_API_URL="${{ secrets.ROOT_API_URL }}"
            
            export SMTP_DELIVERY_METHOD="smtp"
            export SMTP_USER_NAME="${{ secrets.SMTP_USER_NAME }}"
            export SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}"
            export SMTP_HOST="${{ secrets.SMTP_HOST }}"
            export SMTP_PORT="${{ secrets.SMTP_PORT }}"
            
            export BASE_FRONT_URL="${{ secrets.BASE_NEXT_FRONT_URL }}"
            
            export ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}"
            export ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"
            
            export JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}"

            export GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}"
            export GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}"
            export GOOGLE_ENCODED_SECRET_FILE="${{ secrets.GOOGLE_ENCODED_SECRET_FILE }}"

            export TELEGRAM_BOT='${{ secrets.TELEGRAM_BOT }}'

            export DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'
            export DISCORD_CHANNEL_ID='${{ secrets.DISCORD_CHANNEL_ID }}'

            export REDIS_URL='redis://localhost:6379/11'
            export ACTION_CABLE_URL='ws://localhost:${{ secrets.PORT }}/cable'
            export LANG=C.UTF-8 
            export RAILS_ENV=production
            export RAILS_MIN_THREADS=1
            export RAILS_MAX_THREADS=10
            export WEB_CONCURRENCY=3
            export SIDEKIQ_CONCURRENCY=5
            export LC_CTYPE=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export PORT=${{ secrets.PORT }}
            export PATH="/home/${{ secrets.SSH_USER }}/.rbenv/bin:/home/${{ secrets.SSH_USER }}/.rbenv/shims:$PATH"

            echo "
            DATABASE_HOST='${{ secrets.DATABASE_HOST }}'
            STAGE_DATABASE_NAME='${{ secrets.STAGE_DATABASE_NAME }}'
            DATABASE_NAME='${{ secrets.DATABASE_NAME }}'
            SECRET_KEY_BASE='${{ secrets.SECRET_KEY_BASE }}'
            REDIS_URL='redis://localhost:6379/11'
            ACTION_CABLE_URL='ws://localhost:${{ secrets.PORT }}/cable'
            DATABASE_USER='${{ secrets.DATABASE_USER }}'
            DATABASE_PASSWORD='${{ secrets.DATABASE_PASSWORD }}'
            API_TOOLS_ACCESS_TOKEN='${{ secrets.API_TOOLS_ACCESS_TOKEN }}'
            SMTP_DELIVERY_METHOD='smtp'
            SMTP_USER_NAME='${{ secrets.SMTP_USER_NAME }}'
            SMTP_PASSWORD='${{ secrets.SMTP_PASSWORD }}'
            SMTP_HOST='${{ secrets.SMTP_HOST }}'
            SMTP_PORT='${{ secrets.SMTP_PORT }}'
            BASE_FRONT_URL='${{ secrets.BASE_NEXT_FRONT_URL }}'
            ADMIN_EMAIL='${{ secrets.ADMIN_EMAIL }}'
            ADMIN_PASSWORD='${{ secrets.ADMIN_PASSWORD }}'
            JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}'
            ROOT_API_URL='${{ secrets.ROOT_API_URL }}'
            GOOGLE_CLIENT_ID='${{ secrets.GOOGLE_CLIENT_ID }}'
            GOOGLE_CLIENT_SECRET='${{ secrets.GOOGLE_CLIENT_SECRET }}'
            GOOGLE_ENCODED_SECRET_FILE='${{ secrets.GOOGLE_ENCODED_SECRET_FILE }}'
            TELEGRAM_TOKEN='${{ secrets.TELEGRAM_TOKEN }}'
            DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}'
            DISCORD_CHANNEL_ID='${{ secrets.DISCORD_CHANNEL_ID }}'
            LANG=C.UTF-8 
            RAILS_ENV=production
            RAILS_MIN_THREADS=1
            RAILS_MAX_THREADS=10
            WEB_CONCURRENCY=3
            SIDEKIQ_CONCURRENCY=5
            LC_CTYPE=en_US.UTF-8
            LC_ALL=en_US.UTF-8
            PORT=${{ secrets.PORT }}
            PATH='/home/${{ secrets.SSH_USER }}/.rbenv/bin:/home/${{ secrets.SSH_USER }}/.rbenv/shims:\$PATH\'
            " > /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/.env
            
            rbenv global 3.0.2

            rbenv -v
            ruby -v
            bundle -v

            bundle config --global frozen false
            bundle config set without 'development test'
            bundle config set --local deployment 'true'
            bundle install --without development test -j4 --retry 3

            bundle exec rails db:migrate

            # Restart or start the demo_broadcast_calendar_puma.service
            sudo systemctl restart demo_broadcast_calendar_puma.service || sudo systemctl start demo_broadcast_calendar_puma.service

            # Start Sidekiq
            sudo systemctl restart demo_broadcast_calendar_sidekiq.service || sudo systemctl start demo_broadcast_calendar_sidekiq.service

            # Run tests
            export PATH="$PATH:/home/${{ secrets.SSH_USER }}/.pyenv/bin"

            eval "$(pyenv init -)"

            pyenv local 3.8.0
            
            # cd /home/${{ secrets.SSH_USER }}/autotests/Tests
            # sleep 10
            # env=STAGE /home/${{ secrets.SSH_USER }}/.pyenv/versions/3.8.0/bin/pytest test_endpoints_api.py --alluredir=/home/${{ secrets.SSH_USER }}/autotests/allure_results

            # Restart Allure serve
            # sudo systemctl restart broadcast_calendar_allure.service || sudo systemctl start broadcast_calendar_allure.service

            # Start Telegram poller
            cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/
            /home/${{ secrets.SSH_USER }}/.rbenv/shims/bundle exec ruby ./bin/telegram_bot_ctl restart

            # Start Discord Bot
            cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/
            RAILS_ENV=production /home/${{ secrets.SSH_USER }}/.rbenv/shims/bundle exec ruby ./bin/discord_bot_ctl restart

          EOF
