name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract repository name and owner, and convert to lowercase
        id: extract_repo
        run: |
          echo "::set-output name=repo_name::$(echo ${{ github.repository }} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=repo_owner::$(echo ${{ github.repository }} | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.extract_repo.outputs.repo_owner }}/${{ steps.extract_repo.outputs.repo_name }}:latest

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -T -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<-EOF
            echo "${{ secrets.DOCKER_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker pull ghcr.io/${{ steps.extract_repo.outputs.repo_owner }}/${{ steps.extract_repo.outputs.repo_name }}:latest
            sudo docker stop ${{ steps.extract_repo.outputs.repo_name }} || true
            sudo docker rm ${{ steps.extract_repo.outputs.repo_name }} || true
            sudo docker run -d --name ${{ steps.extract_repo.outputs.repo_name }} \
              --network host \
              -e SENTRY_DSN='${{ secrets.SENTRY_DSN }}' \
              -e PRODUCTION_URL='${{ secrets.PRODUCTION_URL }}' \
              -e STAGING_URL='${{ secrets.STAGING_URL }}' \
              -e DATABASE_HOST='${{ secrets.DATABASE_HOST }}' \
              -e DATABASE_NAME='${{ secrets.DATABASE_NAME }}' \
              -e STAGE_DATABASE_NAME="${{ secrets.STAGE_DATABASE_NAME }}" \
              -e SECRET_KEY_BASE="${{ secrets.SECRET_KEY_BASE }}123" \
              -e DATABASE_USER="${{ secrets.DATABASE_USER}}" \
              -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
              -e API_TOOLS_ACCESS_TOKEN="${{ secrets.API_TOOLS_ACCESS_TOKEN }}" \
              -e ROOT_API_URL="${{ secrets.ROOT_API_URL }}" \
              -e SMTP_DELIVERY_METHOD="smtp" \
              -e SMTP_USER_NAME="${{ secrets.SMTP_USER_NAME }}" \
              -e SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" \
              -e SMTP_HOST="${{ secrets.SMTP_HOST }}" \
              -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
              -e BASE_FRONT_URL="${{ secrets.BASE_FRONT_URL }}" \
              -e ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}" \
              -e ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e GOOGLE_ENCODED_SECRET_FILE="${{ secrets.GOOGLE_ENCODED_SECRET_FILE }}" \
              -e TELEGRAM_BOT='${{ secrets.TELEGRAM_BOT }}' \
              -e DISCORD_TOKEN='${{ secrets.DISCORD_TOKEN }}' \
              -e DISCORD_CHANNEL_ID='${{ secrets.DISCORD_CHANNEL_ID }}' \
              -e REDIS_URL='redis://localhost:6379/11' \
              -e ACTION_CABLE_URL='ws://localhost:${{ secrets.PORT }}/cable' \
              -e LANG=C.UTF-8  \
              -e RAILS_ENV=production \
              -e RAILS_MIN_THREADS=1 \
              -e RAILS_MAX_THREADS=10 \
              -e WEB_CONCURRENCY=3 \
              -e SIDEKIQ_CONCURRENCY=5 \
              -e LC_CTYPE=en_US.UTF-8 \
              -e LC_ALL=en_US.UTF-8 \
              -e PORT=${{ secrets.PORT }} \
              -e PATH="/home/${{ secrets.SSH_USER }}/.rbenv/bin:/home/${{ secrets.SSH_USER }}/.rbenv/shims:$PATH" \
              ghcr.io/${{ steps.extract_repo.outputs.repo_owner }}/${{ steps.extract_repo.outputs.repo_name }}:latest

              rbenv global 3.0.2

              rbenv -v
              ruby -v
              bundle -v

              bundle config --global frozen false
              bundle config set without 'development test'
              bundle config set --local deployment 'true'
              bundle install --without development test -j4 --retry 3

              bundle exec rails db:migrate

              # Restart or start the demo_broadcast_calendar_puma.service
              sudo systemctl restart demo_broadcast_calendar_puma.service || sudo systemctl start demo_broadcast_calendar_puma.service

              # Start Sidekiq
              sudo systemctl restart demo_broadcast_calendar_sidekiq.service || sudo systemctl start demo_broadcast_calendar_sidekiq.service

              # Run tests
              export PATH="$PATH:/home/${{ secrets.SSH_USER }}/.pyenv/bin"

              eval "$(pyenv init -)"

              pyenv local 3.8.0
            
              # cd /home/${{ secrets.SSH_USER }}/autotests/Tests
              # sleep 10
              # env=STAGE /home/${{ secrets.SSH_USER }}/.pyenv/versions/3.8.0/bin/pytest test_endpoints_api.py --alluredir=/home/${{ secrets.SSH_USER }}/autotests/allure_results

              # Restart Allure serve
              # sudo systemctl restart broadcast_calendar_allure.service || sudo systemctl start broadcast_calendar_allure.service

              # Start Telegram poller
              cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/
              /home/${{ secrets.SSH_USER }}/.rbenv/shims/bundle exec ruby ./bin/telegram_bot_ctl restart

              # Start Discord Bot
              cd /home/${{ secrets.SSH_USER }}/${{ secrets.SERVER_APP_FOLDER }}/
              RAILS_ENV=production /home/${{ secrets.SSH_USER }}/.rbenv/shims/bundle exec ruby ./bin/discord_bot_ctl restart
          EOF
